### ISSUE TITLE
Which components of the Hyperion Stack are using Windows?

### ISSUE THREAD

**Issue by nmcaully** [oracle-quickstart/oci-hyperion#1]
Hi, I notice that there is a comment that Windows 2016 is used when building the Hyperion stack. Is this all components or just a subset. Would be grateful for advice.

**Comment by kumar-dhanagopal** [comment]
All the compute instances in the app tier afaik.  [@rishimahajan - pls confirm]

The bastion is a Linux instance though.

**Comment by rishimahajan** [comment]
All compute instances are Windows 2016. The database is PAAS service on Oracle Linux
