### ISSUE TITLE
It looks like the terraform code will create the database on my behalf - will this be DBCS or a VM with the RDBMS installed?

### ISSUE THREAD

**Issue by nmcaully** [oracle-quickstart/oci-hyperion#2]
It would be great to have DBCS used as a move and improve by including a PaaS service.

**Comment by kumar-dhanagopal** [comment]
DBCS (i.e., https://docs.cloud.oracle.com/en-us/iaas/Content/Database/Concepts/overview.htm ).  See modules/dbsystem/db.dbsystem.tf

**Comment by rishimahajan** [comment]
The code creates DBCS(database PAAS service)
