### ISSUE TITLE
bastian host

### ISSUE THREAD

**Issue by kashifmannzoor** [oracle-quickstart/oci-hyperion#4]
I am getting the below error while using the "Using Terraform CLI" option to provision.
![bastian-host-error](https://user-images.githubusercontent.com/42314831/103534307-0e84f980-4ea8-11eb-8161-93435d47dab6.png)
Error: Error applying plan:

1 error(s) occurred:

* module.create_bastion.var.bastion_image: Resource 'data.oci_core_images.InstanceImageOCID' not found for variable 'data.oci_core_images.InstanceImageOCID.images.0.id'

**Comment by rishimahajan** [comment]
@kashifmannzoor-Closing this issue as this couldn't be reproduced using terraform CLI or ORM provisioning. As discussed, please check policy for the user being used for provisioning and retry the operation.
